version: '3' # definição do docker compose

services:
  back:
    build:
      contexto: .
      dockerfile: dockerfile-back
      container_name: back
      ports:
        - "4000:4000"
      networks:
        -
      volumes:
        -
  front:
    build:
      contexto: .
      dockerfile: dockerfile-front
      container_name: front
    ports:
        - "3000:3000"
    networks:
        -
    volumes:
        -
    depends_on:
      - back
networks:
  nome:
    driver: rede_



volumes: